name: portal
services:
  portal_mongo:
    image: mongo
    container_name: Logitar.Portal_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: portal
      MONGO_INITDB_ROOT_PASSWORD: LB6SAj52nU73ZxFz
    ports:
      - 27027:27017
    volumes:
      - mongodata:/data/db

  portal_mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Logitar.Portal_mssql
    restart: unless-stopped
    user: root
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: w8x6pF9H5QEJL7sN
    ports:
      - 1437:1433
    volumes:
      - mssql_backup:/var/opt/mssql/backup
      - mssql_data:/var/opt/mssql/data
      - mssql_log:/var/opt/mssql/log

  portal_postgres:
    image: postgres
    container_name: Logitar.Portal_postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: YStQn6XF5VbgcPBw
    ports:
      - 5437:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  portal_rabbitmq:
    image: masstransit/rabbitmq
    container_name: Logitar.Portal_rabbitmq
    restart: unless-stopped
    ports:
      - 5677:5672
      - 15677:15672

  portal_backend:
    build:
      context: ./backend
      dockerfile: /src/Logitar.Portal/Dockerfile
    image: portal_backend
    container_name: Logitar.Portal_backend
    depends_on:
      - portal_mongo
      - portal_mssql
      - portal_postgres
    restart: unless-stopped
    environment:
      ASPNETCORE_Environment: Development
      MongoDB:ConnectionString: mongodb://portal:LB6SAj52nU73ZxFz@portal_mongo:27017/
      POSTGRESQLCONNSTR_Portal: "User ID=postgres;Password=YStQn6XF5VbgcPBw;Host=portal_postgres;Port=5432;Database=Portal;"
      SQLCONNSTR_Portal: "Server=portal_mssql;Database=Portal;User Id=SA;Password=w8x6pF9H5QEJL7sN;Persist Security Info=False;Encrypt=False;"
    ports:
      - 8087:8080

  portal_worker:
    build:
      context: ./backend
      dockerfile: /src/Logitar.Portal.Worker/Dockerfile
    image: portal_worker
    container_name: Logitar.Portal_worker
    depends_on:
      - portal_mssql
      - portal_postgres
    restart: unless-stopped
    environment:
      DOTNET_ENVIRONMENT: Development
      POSTGRESQLCONNSTR_Portal: "User ID=postgres;Password=YStQn6XF5VbgcPBw;Host=portal_postgres;Port=5432;Database=Portal;"
      SQLCONNSTR_Portal: "Server=portal_mssql;Database=Portal;User Id=SA;Password=w8x6pF9H5QEJL7sN;Persist Security Info=False;Encrypt=False;"

volumes:
  mongodata:
  mssql_backup:
  mssql_data:
  mssql_log:
  postgres_data:
