START TRANSACTION;

CREATE TABLE "Logs" (
    "Sid" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "Method" character varying(10) NOT NULL,
    "Url" character varying(2048) NOT NULL,
    "IpAddress" character varying(40) NULL,
    "StatusCode" integer NULL,
    "StartedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "EndedAt" timestamp with time zone NULL,
    "Duration" interval NULL,
    "ActorId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    "SessionId" uuid NULL,
    "UserId" uuid NULL,
    "Errors" jsonb NULL,
    "HasErrors" boolean NOT NULL DEFAULT FALSE,
    "Succeeded" boolean NOT NULL DEFAULT FALSE,
    "Request" jsonb NULL,
    CONSTRAINT "PK_Logs" PRIMARY KEY ("Sid")
);

CREATE UNIQUE INDEX "IX_Logs_Id" ON "Logs" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220810161521_CreateLogTable', '6.0.7');

COMMIT;
