START TRANSACTION;

CREATE TABLE "Senders" (
    "Sid" integer GENERATED BY DEFAULT AS IDENTITY,
    "RealmSid" integer NULL,
    "IsDefault" boolean NOT NULL DEFAULT FALSE,
    "EmailAddress" character varying(256) NOT NULL,
    "DisplayName" character varying(256) NULL,
    "Provider" integer NOT NULL DEFAULT 0,
    "Settings" jsonb NULL,
    "Id" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Senders" PRIMARY KEY ("Sid"),
    CONSTRAINT "FK_Senders_Realms_RealmSid" FOREIGN KEY ("RealmSid") REFERENCES "Realms" ("Sid")
);

CREATE INDEX "IX_Senders_DisplayName" ON "Senders" ("DisplayName");

CREATE INDEX "IX_Senders_EmailAddress" ON "Senders" ("EmailAddress");

CREATE UNIQUE INDEX "IX_Senders_Id" ON "Senders" ("Id");

CREATE INDEX "IX_Senders_IsDefault" ON "Senders" ("IsDefault");

CREATE INDEX "IX_Senders_Provider" ON "Senders" ("Provider");

CREATE INDEX "IX_Senders_RealmSid" ON "Senders" ("RealmSid");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220729014222_CreateSenderTable', '6.0.7');

COMMIT;
