START TRANSACTION;

CREATE TABLE "Actors" (
    "Sid" integer GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "Type" integer NOT NULL,
    "Name" character varying(256) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "Email" character varying(256) NULL,
    "Picture" character varying(2048) NULL,
    CONSTRAINT "PK_Actors" PRIMARY KEY ("Sid")
);

CREATE UNIQUE INDEX "IX_Actors_Id" ON "Actors" ("Id");

CREATE INDEX "IX_Actors_Type" ON "Actors" ("Type");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220807181543_CreateActorTable', '6.0.7');

COMMIT;
