START TRANSACTION;

DROP INDEX "IX_Users_EmailNormalized";

CREATE TABLE "Templates" (
    "Sid" integer GENERATED BY DEFAULT AS IDENTITY,
    "RealmSid" integer NULL,
    "Key" character varying(256) NOT NULL,
    "KeyNormalized" character varying(256) NOT NULL,
    "Contents" text NOT NULL,
    "DisplayName" character varying(256) NULL,
    "Description" text NULL,
    "Id" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Templates" PRIMARY KEY ("Sid"),
    CONSTRAINT "FK_Templates_Realms_RealmSid" FOREIGN KEY ("RealmSid") REFERENCES "Realms" ("Sid")
);

CREATE INDEX "IX_Templates_DisplayName" ON "Templates" ("DisplayName");

CREATE UNIQUE INDEX "IX_Templates_Id" ON "Templates" ("Id");

CREATE INDEX "IX_Templates_Key" ON "Templates" ("Key");

CREATE UNIQUE INDEX "IX_Templates_RealmSid_KeyNormalized" ON "Templates" ("RealmSid", "KeyNormalized");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220728190623_CreateTemplateTable', '6.0.7');

COMMIT;
