START TRANSACTION;

CREATE TABLE "Messages" (
    "Sid" integer GENERATED BY DEFAULT AS IDENTITY,
    "Body" text NOT NULL,
    "Recipients" jsonb NOT NULL,
    "SenderId" uuid NOT NULL,
    "SenderIsDefault" boolean NOT NULL,
    "SenderProvider" integer NOT NULL,
    "SenderAddress" character varying(256) NOT NULL,
    "SenderDisplayName" character varying(256) NULL,
    "RealmId" uuid NULL,
    "RealmAlias" character varying(256) NULL,
    "RealmName" character varying(256) NULL,
    "TemplateId" uuid NOT NULL,
    "TemplateKey" character varying(256) NOT NULL,
    "TemplateSubject" character varying(256) NOT NULL,
    "TemplateContentType" character varying(256) NOT NULL,
    "TemplateDisplayName" character varying(256) NULL,
    "Errors" jsonb NULL,
    "HasErrors" boolean NOT NULL,
    "Result" jsonb NULL,
    "Succeeded" boolean NOT NULL,
    "Variables" jsonb NULL,
    "Id" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Sid")
);

CREATE INDEX "IX_Messages_HasErrors" ON "Messages" ("HasErrors");

CREATE UNIQUE INDEX "IX_Messages_Id" ON "Messages" ("Id");

CREATE INDEX "IX_Messages_RealmAlias" ON "Messages" ("RealmAlias");

CREATE INDEX "IX_Messages_RealmId" ON "Messages" ("RealmId");

CREATE INDEX "IX_Messages_RealmName" ON "Messages" ("RealmName");

CREATE INDEX "IX_Messages_SenderAddress" ON "Messages" ("SenderAddress");

CREATE INDEX "IX_Messages_SenderDisplayName" ON "Messages" ("SenderDisplayName");

CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");

CREATE INDEX "IX_Messages_SenderProvider" ON "Messages" ("SenderProvider");

CREATE INDEX "IX_Messages_Succeeded" ON "Messages" ("Succeeded");

CREATE INDEX "IX_Messages_TemplateContentType" ON "Messages" ("TemplateContentType");

CREATE INDEX "IX_Messages_TemplateDisplayName" ON "Messages" ("TemplateDisplayName");

CREATE INDEX "IX_Messages_TemplateId" ON "Messages" ("TemplateId");

CREATE INDEX "IX_Messages_TemplateKey" ON "Messages" ("TemplateKey");

CREATE INDEX "IX_Messages_TemplateSubject" ON "Messages" ("TemplateSubject");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220729185333_CreateMessageTable', '6.0.7');

COMMIT;
