CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Dictionaries" (
    "DictionaryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" uuid,
    "EntityId" uuid NOT NULL,
    "Locale" character varying(16) NOT NULL,
    "LocaleNormalized" character varying(16) NOT NULL,
    "EntryCount" integer NOT NULL,
    "Entries" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Dictionaries" PRIMARY KEY ("DictionaryId")
);

CREATE TABLE "Logs" (
    "LogId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UniqueId" uuid NOT NULL,
    "CorrelationId" character varying(255),
    "Method" character varying(255),
    "Destination" character varying(2048),
    "Source" character varying(2048),
    "AdditionalInformation" text,
    "OperationType" character varying(255),
    "OperationName" character varying(255),
    "ActivityType" character varying(255),
    "ActivityData" text,
    "StatusCode" integer,
    "IsCompleted" boolean NOT NULL,
    "Level" character varying(255) NOT NULL,
    "HasErrors" boolean NOT NULL,
    "StartedOn" timestamp with time zone NOT NULL,
    "EndedOn" timestamp with time zone,
    "Duration" interval,
    "TenantId" uuid,
    "ActorId" character varying(255),
    "ApiKeyId" uuid,
    "UserId" uuid,
    "SessionId" uuid,
    CONSTRAINT "PK_Logs" PRIMARY KEY ("LogId")
);

CREATE TABLE "Realms" (
    "RealmId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UniqueSlug" character varying(255) NOT NULL,
    "UniqueSlugNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255),
    "Description" text,
    "DefaultLocale" character varying(16),
    "Secret" character varying(64) NOT NULL,
    "Url" character varying(2048),
    "AllowedUniqueNameCharacters" character varying(255),
    "RequiredPasswordLength" integer NOT NULL,
    "RequiredPasswordUniqueChars" integer NOT NULL,
    "PasswordsRequireNonAlphanumeric" boolean NOT NULL,
    "PasswordsRequireLowercase" boolean NOT NULL,
    "PasswordsRequireUppercase" boolean NOT NULL,
    "PasswordsRequireDigit" boolean NOT NULL,
    "PasswordHashingStrategy" character varying(255) NOT NULL,
    "RequireUniqueEmail" boolean NOT NULL,
    "CustomAttributes" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Realms" PRIMARY KEY ("RealmId")
);

CREATE TABLE "Senders" (
    "SenderId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" uuid,
    "EntityId" uuid NOT NULL,
    "IsDefault" boolean NOT NULL,
    "EmailAddress" character varying(255),
    "PhoneNumber" character varying(20),
    "DisplayName" character varying(255),
    "Description" text,
    "Provider" character varying(255) NOT NULL,
    "Settings" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Senders" PRIMARY KEY ("SenderId")
);

CREATE TABLE "Templates" (
    "TemplateId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" uuid,
    "EntityId" uuid NOT NULL,
    "UniqueKey" character varying(255) NOT NULL,
    "UniqueKeyNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255),
    "Description" text,
    "Subject" character varying(255) NOT NULL,
    "ContentType" character varying(10) NOT NULL,
    "ContentText" text NOT NULL,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Templates" PRIMARY KEY ("TemplateId")
);

CREATE TABLE "LogEvents" (
    "EventId" uuid NOT NULL,
    "LogId" bigint NOT NULL,
    CONSTRAINT "PK_LogEvents" PRIMARY KEY ("EventId"),
    CONSTRAINT "FK_LogEvents_Logs_LogId" FOREIGN KEY ("LogId") REFERENCES "Logs" ("LogId") ON DELETE CASCADE
);

CREATE TABLE "LogExceptions" (
    "LogExceptionId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "LogId" bigint NOT NULL,
    "Type" character varying(255) NOT NULL,
    "Message" text NOT NULL,
    "HResult" integer NOT NULL,
    "HelpLink" text,
    "Source" text,
    "StackTrace" text,
    "TargetSite" text,
    "Data" text,
    CONSTRAINT "PK_LogExceptions" PRIMARY KEY ("LogExceptionId"),
    CONSTRAINT "FK_LogExceptions_Logs_LogId" FOREIGN KEY ("LogId") REFERENCES "Logs" ("LogId") ON DELETE CASCADE
);

CREATE TABLE "Messages" (
    "MessageId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" uuid,
    "EntityId" uuid NOT NULL,
    "Subject" character varying(255) NOT NULL,
    "BodyType" character varying(10) NOT NULL,
    "BodyText" text NOT NULL,
    "RecipientCount" integer NOT NULL,
    "SenderId" integer,
    "SenderIsDefault" boolean NOT NULL,
    "SenderAddress" character varying(255),
    "SenderPhoneNumber" character varying(20),
    "SenderDisplayName" character varying(255),
    "SenderProvider" character varying(255) NOT NULL,
    "TemplateId" integer,
    "TemplateUniqueKey" character varying(255) NOT NULL,
    "TemplateDisplayName" character varying(255),
    "IgnoreUserLocale" boolean NOT NULL,
    "Locale" character varying(16),
    "Variables" text,
    "IsDemo" boolean NOT NULL,
    "Status" character varying(255) NOT NULL,
    "ResultData" text,
    "StreamId" character varying(255) NOT NULL,
    "Version" bigint NOT NULL,
    "CreatedBy" character varying(255),
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255),
    "UpdatedOn" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("MessageId"),
    CONSTRAINT "FK_Messages_Senders_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Senders" ("SenderId") ON DELETE SET NULL,
    CONSTRAINT "FK_Messages_Templates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES "Templates" ("TemplateId") ON DELETE SET NULL
);

CREATE TABLE "Recipients" (
    "RecipientId" integer GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" integer NOT NULL,
    "Type" character varying(3) NOT NULL,
    "Address" character varying(255),
    "DisplayName" character varying(255),
    "PhoneNumber" character varying(20),
    "UserId" integer,
    "UserUniqueName" character varying(255),
    "UserEmailAddress" character varying(255),
    "UserFullName" character varying(767),
    "UserPicture" character varying(2048),
    CONSTRAINT "PK_Recipients" PRIMARY KEY ("RecipientId"),
    CONSTRAINT "FK_Recipients_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("MessageId") ON DELETE CASCADE
);

CREATE INDEX "IX_Dictionaries_CreatedBy" ON "Dictionaries" ("CreatedBy");

CREATE INDEX "IX_Dictionaries_CreatedOn" ON "Dictionaries" ("CreatedOn");

CREATE INDEX "IX_Dictionaries_EntityId" ON "Dictionaries" ("EntityId");

CREATE INDEX "IX_Dictionaries_EntryCount" ON "Dictionaries" ("EntryCount");

CREATE INDEX "IX_Dictionaries_Locale" ON "Dictionaries" ("Locale");

CREATE UNIQUE INDEX "IX_Dictionaries_StreamId" ON "Dictionaries" ("StreamId");

CREATE UNIQUE INDEX "IX_Dictionaries_TenantId_EntityId" ON "Dictionaries" ("TenantId", "EntityId");

CREATE UNIQUE INDEX "IX_Dictionaries_TenantId_LocaleNormalized" ON "Dictionaries" ("TenantId", "LocaleNormalized");

CREATE INDEX "IX_Dictionaries_UpdatedBy" ON "Dictionaries" ("UpdatedBy");

CREATE INDEX "IX_Dictionaries_UpdatedOn" ON "Dictionaries" ("UpdatedOn");

CREATE INDEX "IX_Dictionaries_Version" ON "Dictionaries" ("Version");

CREATE INDEX "IX_LogEvents_LogId" ON "LogEvents" ("LogId");

CREATE INDEX "IX_LogExceptions_LogId" ON "LogExceptions" ("LogId");

CREATE INDEX "IX_LogExceptions_Type" ON "LogExceptions" ("Type");

CREATE INDEX "IX_Logs_ActivityType" ON "Logs" ("ActivityType");

CREATE INDEX "IX_Logs_ActorId" ON "Logs" ("ActorId");

CREATE INDEX "IX_Logs_ApiKeyId" ON "Logs" ("ApiKeyId");

CREATE INDEX "IX_Logs_CorrelationId" ON "Logs" ("CorrelationId");

CREATE INDEX "IX_Logs_Duration" ON "Logs" ("Duration");

CREATE INDEX "IX_Logs_EndedOn" ON "Logs" ("EndedOn");

CREATE INDEX "IX_Logs_HasErrors" ON "Logs" ("HasErrors");

CREATE INDEX "IX_Logs_IsCompleted" ON "Logs" ("IsCompleted");

CREATE INDEX "IX_Logs_Level" ON "Logs" ("Level");

CREATE INDEX "IX_Logs_OperationName" ON "Logs" ("OperationName");

CREATE INDEX "IX_Logs_OperationType" ON "Logs" ("OperationType");

CREATE INDEX "IX_Logs_SessionId" ON "Logs" ("SessionId");

CREATE INDEX "IX_Logs_StartedOn" ON "Logs" ("StartedOn");

CREATE INDEX "IX_Logs_StatusCode" ON "Logs" ("StatusCode");

CREATE INDEX "IX_Logs_TenantId" ON "Logs" ("TenantId");

CREATE UNIQUE INDEX "IX_Logs_UniqueId" ON "Logs" ("UniqueId");

CREATE INDEX "IX_Logs_UserId" ON "Logs" ("UserId");

CREATE INDEX "IX_Messages_CreatedBy" ON "Messages" ("CreatedBy");

CREATE INDEX "IX_Messages_CreatedOn" ON "Messages" ("CreatedOn");

CREATE INDEX "IX_Messages_EntityId" ON "Messages" ("EntityId");

CREATE INDEX "IX_Messages_IsDemo" ON "Messages" ("IsDemo");

CREATE INDEX "IX_Messages_RecipientCount" ON "Messages" ("RecipientCount");

CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");

CREATE INDEX "IX_Messages_Status" ON "Messages" ("Status");

CREATE UNIQUE INDEX "IX_Messages_StreamId" ON "Messages" ("StreamId");

CREATE INDEX "IX_Messages_Subject" ON "Messages" ("Subject");

CREATE INDEX "IX_Messages_TemplateId" ON "Messages" ("TemplateId");

CREATE UNIQUE INDEX "IX_Messages_TenantId_EntityId" ON "Messages" ("TenantId", "EntityId");

CREATE INDEX "IX_Messages_UpdatedBy" ON "Messages" ("UpdatedBy");

CREATE INDEX "IX_Messages_UpdatedOn" ON "Messages" ("UpdatedOn");

CREATE INDEX "IX_Messages_Version" ON "Messages" ("Version");

CREATE INDEX "IX_Realms_CreatedBy" ON "Realms" ("CreatedBy");

CREATE INDEX "IX_Realms_CreatedOn" ON "Realms" ("CreatedOn");

CREATE INDEX "IX_Realms_DisplayName" ON "Realms" ("DisplayName");

CREATE UNIQUE INDEX "IX_Realms_StreamId" ON "Realms" ("StreamId");

CREATE INDEX "IX_Realms_UniqueSlug" ON "Realms" ("UniqueSlug");

CREATE UNIQUE INDEX "IX_Realms_UniqueSlugNormalized" ON "Realms" ("UniqueSlugNormalized");

CREATE INDEX "IX_Realms_UpdatedBy" ON "Realms" ("UpdatedBy");

CREATE INDEX "IX_Realms_UpdatedOn" ON "Realms" ("UpdatedOn");

CREATE INDEX "IX_Realms_Version" ON "Realms" ("Version");

CREATE INDEX "IX_Recipients_Address" ON "Recipients" ("Address");

CREATE INDEX "IX_Recipients_DisplayName" ON "Recipients" ("DisplayName");

CREATE INDEX "IX_Recipients_MessageId" ON "Recipients" ("MessageId");

CREATE INDEX "IX_Recipients_PhoneNumber" ON "Recipients" ("PhoneNumber");

CREATE INDEX "IX_Recipients_Type" ON "Recipients" ("Type");

CREATE INDEX "IX_Recipients_UserId" ON "Recipients" ("UserId");

CREATE INDEX "IX_Senders_CreatedBy" ON "Senders" ("CreatedBy");

CREATE INDEX "IX_Senders_CreatedOn" ON "Senders" ("CreatedOn");

CREATE INDEX "IX_Senders_DisplayName" ON "Senders" ("DisplayName");

CREATE INDEX "IX_Senders_EmailAddress" ON "Senders" ("EmailAddress");

CREATE INDEX "IX_Senders_EntityId" ON "Senders" ("EntityId");

CREATE INDEX "IX_Senders_PhoneNumber" ON "Senders" ("PhoneNumber");

CREATE INDEX "IX_Senders_Provider" ON "Senders" ("Provider");

CREATE UNIQUE INDEX "IX_Senders_StreamId" ON "Senders" ("StreamId");

CREATE UNIQUE INDEX "IX_Senders_TenantId_EntityId" ON "Senders" ("TenantId", "EntityId");

CREATE INDEX "IX_Senders_TenantId_IsDefault" ON "Senders" ("TenantId", "IsDefault");

CREATE INDEX "IX_Senders_UpdatedBy" ON "Senders" ("UpdatedBy");

CREATE INDEX "IX_Senders_UpdatedOn" ON "Senders" ("UpdatedOn");

CREATE INDEX "IX_Senders_Version" ON "Senders" ("Version");

CREATE INDEX "IX_Templates_ContentType" ON "Templates" ("ContentType");

CREATE INDEX "IX_Templates_CreatedBy" ON "Templates" ("CreatedBy");

CREATE INDEX "IX_Templates_CreatedOn" ON "Templates" ("CreatedOn");

CREATE INDEX "IX_Templates_DisplayName" ON "Templates" ("DisplayName");

CREATE INDEX "IX_Templates_EntityId" ON "Templates" ("EntityId");

CREATE UNIQUE INDEX "IX_Templates_StreamId" ON "Templates" ("StreamId");

CREATE INDEX "IX_Templates_Subject" ON "Templates" ("Subject");

CREATE UNIQUE INDEX "IX_Templates_TenantId_EntityId" ON "Templates" ("TenantId", "EntityId");

CREATE UNIQUE INDEX "IX_Templates_TenantId_UniqueKeyNormalized" ON "Templates" ("TenantId", "UniqueKeyNormalized");

CREATE INDEX "IX_Templates_UniqueKey" ON "Templates" ("UniqueKey");

CREATE INDEX "IX_Templates_UpdatedBy" ON "Templates" ("UpdatedBy");

CREATE INDEX "IX_Templates_UpdatedOn" ON "Templates" ("UpdatedOn");

CREATE INDEX "IX_Templates_Version" ON "Templates" ("Version");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241224061447_Release_5_0_0', '9.0.0');

COMMIT;
