CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Actors" (
    "ActorId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "Type" character varying(255) NOT NULL,
    "IsDeleted" boolean NOT NULL,
    "DisplayName" character varying(255) NOT NULL,
    "EmailAddress" character varying(255) NULL,
    "PictureUrl" character varying(2048) NULL,
    CONSTRAINT "PK_Actors" PRIMARY KEY ("ActorId")
);

CREATE TABLE "ApiKeys" (
    "ApiKeyId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255) NULL,
    "Secret" character varying(255) NULL,
    "DisplayName" character varying(255) NOT NULL,
    "Description" text NULL,
    "ExpiresOn" timestamp with time zone NULL,
    "AuthenticatedOn" timestamp with time zone NULL,
    "CustomAttributes" text NULL,
    "AggregateId" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_ApiKeys" PRIMARY KEY ("ApiKeyId")
);

CREATE TABLE "Dictionaries" (
    "DictionaryId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255) NULL,
    "Locale" character varying(16) NOT NULL,
    "EntriesSerialized" text NULL,
    "EntryCount" integer NOT NULL,
    "AggregateId" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_Dictionaries" PRIMARY KEY ("DictionaryId")
);

CREATE TABLE "Logs" (
    "LogId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "CorrelationId" character varying(255) NULL,
    "Method" character varying(255) NULL,
    "Destination" character varying(2048) NULL,
    "Source" character varying(2048) NULL,
    "AdditionalInformation" text NULL,
    "OperationType" character varying(255) NULL,
    "OperationName" character varying(255) NULL,
    "ActivityType" character varying(255) NULL,
    "ActivityData" text NULL,
    "StatusCode" integer NULL,
    "StartedOn" timestamp with time zone NOT NULL,
    "EndedOn" timestamp with time zone NULL,
    "Duration" interval NULL,
    "ActorId" uuid NOT NULL,
    "UserId" uuid NULL,
    "SessionId" uuid NULL,
    "IsCompleted" boolean NOT NULL,
    "Level" character varying(255) NOT NULL,
    "HasErrors" boolean NOT NULL,
    "Errors" text NULL,
    CONSTRAINT "PK_Logs" PRIMARY KEY ("LogId")
);

CREATE TABLE "Roles" (
    "RoleId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255) NULL,
    "UniqueName" character varying(255) NOT NULL,
    "UniqueNameNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255) NULL,
    "Description" text NULL,
    "CustomAttributes" text NULL,
    "AggregateId" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("RoleId")
);

CREATE TABLE "Senders" (
    "SenderId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255) NULL,
    "IsDefault" boolean NOT NULL,
    "EmailAddress" character varying(255) NOT NULL,
    "DisplayName" character varying(255) NULL,
    "Description" text NULL,
    "Provider" character varying(255) NOT NULL,
    "Settings" text NULL,
    "AggregateId" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_Senders" PRIMARY KEY ("SenderId")
);

CREATE TABLE "Templates" (
    "TemplateId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255) NULL,
    "UniqueName" character varying(255) NOT NULL,
    "UniqueNameNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255) NULL,
    "Description" text NULL,
    "Subject" character varying(255) NOT NULL,
    "ContentType" character varying(16) NOT NULL,
    "Contents" text NOT NULL,
    "AggregateId" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_Templates" PRIMARY KEY ("TemplateId")
);

CREATE TABLE "TokenBlacklist" (
    "BlacklistedTokenId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "ExpiresOn" timestamp with time zone NULL,
    CONSTRAINT "PK_TokenBlacklist" PRIMARY KEY ("BlacklistedTokenId")
);

CREATE TABLE "Users" (
    "UserId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255) NULL,
    "UniqueName" character varying(255) NOT NULL,
    "UniqueNameNormalized" character varying(255) NOT NULL,
    "HasPassword" boolean NOT NULL,
    "Password" character varying(255) NULL,
    "PasswordChangedBy" character varying(255) NULL,
    "PasswordChangedOn" timestamp with time zone NULL,
    "DisabledBy" character varying(255) NULL,
    "DisabledOn" timestamp with time zone NULL,
    "IsDisabled" boolean NOT NULL,
    "AuthenticatedOn" timestamp with time zone NULL,
    "AddressStreet" character varying(255) NULL,
    "AddressLocality" character varying(255) NULL,
    "AddressRegion" character varying(255) NULL,
    "AddressPostalCode" character varying(255) NULL,
    "AddressCountry" character varying(255) NULL,
    "AddressFormatted" character varying(1536) NULL,
    "AddressVerifiedBy" character varying(255) NULL,
    "AddressVerifiedOn" timestamp with time zone NULL,
    "IsAddressVerified" boolean NOT NULL,
    "EmailAddress" character varying(255) NULL,
    "EmailAddressNormalized" character varying(255) NULL,
    "EmailVerifiedBy" character varying(255) NULL,
    "EmailVerifiedOn" timestamp with time zone NULL,
    "IsEmailVerified" boolean NOT NULL,
    "PhoneCountryCode" character varying(16) NULL,
    "PhoneNumber" character varying(32) NULL,
    "PhoneExtension" character varying(16) NULL,
    "PhoneE164Formatted" character varying(16) NULL,
    "PhoneVerifiedBy" character varying(255) NULL,
    "PhoneVerifiedOn" timestamp with time zone NULL,
    "IsPhoneVerified" boolean NOT NULL,
    "IsConfirmed" boolean NOT NULL,
    "FirstName" character varying(255) NULL,
    "MiddleName" character varying(255) NULL,
    "LastName" character varying(255) NULL,
    "FullName" character varying(768) NULL,
    "Nickname" character varying(255) NULL,
    "Birthdate" timestamp with time zone NULL,
    "Gender" character varying(255) NULL,
    "Locale" character varying(16) NULL,
    "TimeZone" character varying(255) NULL,
    "Picture" character varying(2048) NULL,
    "Profile" character varying(2048) NULL,
    "Website" character varying(2048) NULL,
    "CustomAttributes" text NULL,
    "AggregateId" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
);

CREATE TABLE "LogEvents" (
    "LogId" bigint NOT NULL,
    "EventId" bigint NOT NULL,
    CONSTRAINT "PK_LogEvents" PRIMARY KEY ("LogId", "EventId"),
    CONSTRAINT "FK_LogEvents_Logs_LogId" FOREIGN KEY ("LogId") REFERENCES "Logs" ("LogId") ON DELETE CASCADE
);

CREATE TABLE "ApiKeyRoles" (
    "ApiKeyId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_ApiKeyRoles" PRIMARY KEY ("ApiKeyId", "RoleId"),
    CONSTRAINT "FK_ApiKeyRoles_ApiKeys_ApiKeyId" FOREIGN KEY ("ApiKeyId") REFERENCES "ApiKeys" ("ApiKeyId") ON DELETE CASCADE,
    CONSTRAINT "FK_ApiKeyRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") ON DELETE CASCADE
);

CREATE TABLE "Realms" (
    "RealmId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UniqueSlug" character varying(255) NOT NULL,
    "UniqueSlugNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255) NULL,
    "Description" text NULL,
    "DefaultLocale" character varying(16) NULL,
    "Secret" character varying(64) NOT NULL,
    "Url" character varying(2048) NULL,
    "RequireUniqueEmail" boolean NOT NULL,
    "RequireConfirmedAccount" boolean NOT NULL,
    "AllowedUniqueNameCharacters" character varying(255) NULL,
    "RequiredPasswordLength" integer NOT NULL,
    "RequiredPasswordUniqueChars" integer NOT NULL,
    "PasswordsRequireNonAlphanumeric" boolean NOT NULL,
    "PasswordsRequireLowercase" boolean NOT NULL,
    "PasswordsRequireUppercase" boolean NOT NULL,
    "PasswordsRequireDigit" boolean NOT NULL,
    "PasswordStrategy" character varying(255) NOT NULL,
    "ClaimMappings" text NULL,
    "CustomAttributes" text NULL,
    "PasswordRecoverySenderId" integer NULL,
    "PasswordRecoveryTemplateId" integer NULL,
    "AggregateId" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_Realms" PRIMARY KEY ("RealmId"),
    CONSTRAINT "FK_Realms_Senders_PasswordRecoverySenderId" FOREIGN KEY ("PasswordRecoverySenderId") REFERENCES "Senders" ("SenderId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Realms_Templates_PasswordRecoveryTemplateId" FOREIGN KEY ("PasswordRecoveryTemplateId") REFERENCES "Templates" ("TemplateId") ON DELETE RESTRICT
);

CREATE TABLE "Sessions" (
    "SessionId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "IsPersistent" boolean NOT NULL,
    "Secret" character varying(255) NULL,
    "IsActive" boolean NOT NULL,
    "SignedOutBy" character varying(255) NULL,
    "SignedOutOn" timestamp with time zone NULL,
    "CustomAttributes" text NULL,
    "AggregateId" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_Sessions" PRIMARY KEY ("SessionId"),
    CONSTRAINT "FK_Sessions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE RESTRICT
);

CREATE TABLE "UserIdentifiers" (
    "UserIdentifierId" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Id" uuid NOT NULL,
    "TenantId" character varying(255) NULL,
    "Key" character varying(255) NOT NULL,
    "Value" character varying(255) NOT NULL,
    "ValueNormalized" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_UserIdentifiers" PRIMARY KEY ("UserIdentifierId"),
    CONSTRAINT "FK_UserIdentifiers_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "UserRoles" (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("RoleId") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE CASCADE
);

CREATE TABLE "Messages" (
    "MessageId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Subject" character varying(255) NOT NULL,
    "Body" text NOT NULL,
    "RecipientCount" integer NOT NULL,
    "RealmId" integer NULL,
    "SenderId" integer NULL,
    "SenderSummary" text NOT NULL,
    "TemplateId" integer NULL,
    "TemplateSummary" text NOT NULL,
    "IgnoreUserLocale" boolean NOT NULL,
    "Locale" character varying(16) NULL,
    "Variables" text NULL,
    "IsDemo" boolean NOT NULL,
    "Result" text NULL,
    "Status" character varying(255) NOT NULL,
    "AggregateId" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("MessageId"),
    CONSTRAINT "FK_Messages_Realms_RealmId" FOREIGN KEY ("RealmId") REFERENCES "Realms" ("RealmId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Messages_Senders_SenderId" FOREIGN KEY ("SenderId") REFERENCES "Senders" ("SenderId") ON DELETE SET NULL,
    CONSTRAINT "FK_Messages_Templates_TemplateId" FOREIGN KEY ("TemplateId") REFERENCES "Templates" ("TemplateId") ON DELETE SET NULL
);

CREATE TABLE "Recipients" (
    "RecipientId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" integer NOT NULL,
    "Type" character varying(255) NOT NULL,
    "Address" character varying(255) NOT NULL,
    "DisplayName" character varying(255) NULL,
    "UserId" integer NULL,
    "UserSummary" text NULL,
    CONSTRAINT "PK_Recipients" PRIMARY KEY ("RecipientId"),
    CONSTRAINT "FK_Recipients_Messages_MessageId" FOREIGN KEY ("MessageId") REFERENCES "Messages" ("MessageId") ON DELETE CASCADE,
    CONSTRAINT "FK_Recipients_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("UserId") ON DELETE SET NULL
);

CREATE INDEX "IX_Actors_DisplayName" ON "Actors" ("DisplayName");

CREATE INDEX "IX_Actors_EmailAddress" ON "Actors" ("EmailAddress");

CREATE UNIQUE INDEX "IX_Actors_Id" ON "Actors" ("Id");

CREATE INDEX "IX_Actors_IsDeleted" ON "Actors" ("IsDeleted");

CREATE INDEX "IX_Actors_Type" ON "Actors" ("Type");

CREATE INDEX "IX_ApiKeyRoles_RoleId" ON "ApiKeyRoles" ("RoleId");

CREATE UNIQUE INDEX "IX_ApiKeys_AggregateId" ON "ApiKeys" ("AggregateId");

CREATE INDEX "IX_ApiKeys_AuthenticatedOn" ON "ApiKeys" ("AuthenticatedOn");

CREATE INDEX "IX_ApiKeys_CreatedBy" ON "ApiKeys" ("CreatedBy");

CREATE INDEX "IX_ApiKeys_CreatedOn" ON "ApiKeys" ("CreatedOn");

CREATE INDEX "IX_ApiKeys_DisplayName" ON "ApiKeys" ("DisplayName");

CREATE INDEX "IX_ApiKeys_ExpiresOn" ON "ApiKeys" ("ExpiresOn");

CREATE INDEX "IX_ApiKeys_TenantId" ON "ApiKeys" ("TenantId");

CREATE INDEX "IX_ApiKeys_UpdatedBy" ON "ApiKeys" ("UpdatedBy");

CREATE INDEX "IX_ApiKeys_UpdatedOn" ON "ApiKeys" ("UpdatedOn");

CREATE INDEX "IX_ApiKeys_Version" ON "ApiKeys" ("Version");

CREATE UNIQUE INDEX "IX_Dictionaries_AggregateId" ON "Dictionaries" ("AggregateId");

CREATE INDEX "IX_Dictionaries_CreatedBy" ON "Dictionaries" ("CreatedBy");

CREATE INDEX "IX_Dictionaries_CreatedOn" ON "Dictionaries" ("CreatedOn");

CREATE INDEX "IX_Dictionaries_EntryCount" ON "Dictionaries" ("EntryCount");

CREATE INDEX "IX_Dictionaries_TenantId" ON "Dictionaries" ("TenantId");

CREATE UNIQUE INDEX "IX_Dictionaries_TenantId_Locale" ON "Dictionaries" ("TenantId", "Locale");

CREATE INDEX "IX_Dictionaries_UpdatedBy" ON "Dictionaries" ("UpdatedBy");

CREATE INDEX "IX_Dictionaries_UpdatedOn" ON "Dictionaries" ("UpdatedOn");

CREATE INDEX "IX_Dictionaries_Version" ON "Dictionaries" ("Version");

CREATE INDEX "IX_Logs_ActivityType" ON "Logs" ("ActivityType");

CREATE INDEX "IX_Logs_ActorId" ON "Logs" ("ActorId");

CREATE INDEX "IX_Logs_CorrelationId" ON "Logs" ("CorrelationId");

CREATE INDEX "IX_Logs_Duration" ON "Logs" ("Duration");

CREATE INDEX "IX_Logs_EndedOn" ON "Logs" ("EndedOn");

CREATE INDEX "IX_Logs_HasErrors" ON "Logs" ("HasErrors");

CREATE UNIQUE INDEX "IX_Logs_Id" ON "Logs" ("Id");

CREATE INDEX "IX_Logs_IsCompleted" ON "Logs" ("IsCompleted");

CREATE INDEX "IX_Logs_Level" ON "Logs" ("Level");

CREATE INDEX "IX_Logs_Method" ON "Logs" ("Method");

CREATE INDEX "IX_Logs_OperationName" ON "Logs" ("OperationName");

CREATE INDEX "IX_Logs_OperationType" ON "Logs" ("OperationType");

CREATE INDEX "IX_Logs_SessionId" ON "Logs" ("SessionId");

CREATE INDEX "IX_Logs_StartedOn" ON "Logs" ("StartedOn");

CREATE INDEX "IX_Logs_StatusCode" ON "Logs" ("StatusCode");

CREATE INDEX "IX_Logs_UserId" ON "Logs" ("UserId");

CREATE UNIQUE INDEX "IX_Messages_AggregateId" ON "Messages" ("AggregateId");

CREATE INDEX "IX_Messages_CreatedBy" ON "Messages" ("CreatedBy");

CREATE INDEX "IX_Messages_CreatedOn" ON "Messages" ("CreatedOn");

CREATE INDEX "IX_Messages_IsDemo" ON "Messages" ("IsDemo");

CREATE INDEX "IX_Messages_RealmId" ON "Messages" ("RealmId");

CREATE INDEX "IX_Messages_RecipientCount" ON "Messages" ("RecipientCount");

CREATE INDEX "IX_Messages_SenderId" ON "Messages" ("SenderId");

CREATE INDEX "IX_Messages_Status" ON "Messages" ("Status");

CREATE INDEX "IX_Messages_Subject" ON "Messages" ("Subject");

CREATE INDEX "IX_Messages_TemplateId" ON "Messages" ("TemplateId");

CREATE INDEX "IX_Messages_UpdatedBy" ON "Messages" ("UpdatedBy");

CREATE INDEX "IX_Messages_UpdatedOn" ON "Messages" ("UpdatedOn");

CREATE INDEX "IX_Messages_Version" ON "Messages" ("Version");

CREATE UNIQUE INDEX "IX_Realms_AggregateId" ON "Realms" ("AggregateId");

CREATE INDEX "IX_Realms_CreatedBy" ON "Realms" ("CreatedBy");

CREATE INDEX "IX_Realms_CreatedOn" ON "Realms" ("CreatedOn");

CREATE INDEX "IX_Realms_DisplayName" ON "Realms" ("DisplayName");

CREATE UNIQUE INDEX "IX_Realms_PasswordRecoverySenderId" ON "Realms" ("PasswordRecoverySenderId");

CREATE UNIQUE INDEX "IX_Realms_PasswordRecoveryTemplateId" ON "Realms" ("PasswordRecoveryTemplateId");

CREATE INDEX "IX_Realms_UniqueSlug" ON "Realms" ("UniqueSlug");

CREATE UNIQUE INDEX "IX_Realms_UniqueSlugNormalized" ON "Realms" ("UniqueSlugNormalized");

CREATE INDEX "IX_Realms_UpdatedBy" ON "Realms" ("UpdatedBy");

CREATE INDEX "IX_Realms_UpdatedOn" ON "Realms" ("UpdatedOn");

CREATE INDEX "IX_Realms_Version" ON "Realms" ("Version");

CREATE INDEX "IX_Recipients_MessageId" ON "Recipients" ("MessageId");

CREATE INDEX "IX_Recipients_UserId" ON "Recipients" ("UserId");

CREATE UNIQUE INDEX "IX_Roles_AggregateId" ON "Roles" ("AggregateId");

CREATE INDEX "IX_Roles_CreatedBy" ON "Roles" ("CreatedBy");

CREATE INDEX "IX_Roles_CreatedOn" ON "Roles" ("CreatedOn");

CREATE INDEX "IX_Roles_DisplayName" ON "Roles" ("DisplayName");

CREATE INDEX "IX_Roles_TenantId" ON "Roles" ("TenantId");

CREATE UNIQUE INDEX "IX_Roles_TenantId_UniqueNameNormalized" ON "Roles" ("TenantId", "UniqueNameNormalized");

CREATE INDEX "IX_Roles_UniqueName" ON "Roles" ("UniqueName");

CREATE INDEX "IX_Roles_UpdatedBy" ON "Roles" ("UpdatedBy");

CREATE INDEX "IX_Roles_UpdatedOn" ON "Roles" ("UpdatedOn");

CREATE INDEX "IX_Roles_Version" ON "Roles" ("Version");

CREATE UNIQUE INDEX "IX_Senders_AggregateId" ON "Senders" ("AggregateId");

CREATE INDEX "IX_Senders_CreatedBy" ON "Senders" ("CreatedBy");

CREATE INDEX "IX_Senders_CreatedOn" ON "Senders" ("CreatedOn");

CREATE INDEX "IX_Senders_DisplayName" ON "Senders" ("DisplayName");

CREATE INDEX "IX_Senders_EmailAddress" ON "Senders" ("EmailAddress");

CREATE INDEX "IX_Senders_Provider" ON "Senders" ("Provider");

CREATE INDEX "IX_Senders_TenantId" ON "Senders" ("TenantId");

CREATE UNIQUE INDEX "IX_Senders_TenantId_IsDefault" ON "Senders" ("TenantId", "IsDefault") WHERE "IsDefault" = true;

CREATE INDEX "IX_Senders_UpdatedBy" ON "Senders" ("UpdatedBy");

CREATE INDEX "IX_Senders_UpdatedOn" ON "Senders" ("UpdatedOn");

CREATE INDEX "IX_Senders_Version" ON "Senders" ("Version");

CREATE UNIQUE INDEX "IX_Sessions_AggregateId" ON "Sessions" ("AggregateId");

CREATE INDEX "IX_Sessions_CreatedBy" ON "Sessions" ("CreatedBy");

CREATE INDEX "IX_Sessions_CreatedOn" ON "Sessions" ("CreatedOn");

CREATE INDEX "IX_Sessions_IsActive" ON "Sessions" ("IsActive");

CREATE INDEX "IX_Sessions_IsPersistent" ON "Sessions" ("IsPersistent");

CREATE INDEX "IX_Sessions_SignedOutOn" ON "Sessions" ("SignedOutOn");

CREATE INDEX "IX_Sessions_UpdatedBy" ON "Sessions" ("UpdatedBy");

CREATE INDEX "IX_Sessions_UpdatedOn" ON "Sessions" ("UpdatedOn");

CREATE INDEX "IX_Sessions_UserId" ON "Sessions" ("UserId");

CREATE INDEX "IX_Sessions_Version" ON "Sessions" ("Version");

CREATE UNIQUE INDEX "IX_Templates_AggregateId" ON "Templates" ("AggregateId");

CREATE INDEX "IX_Templates_ContentType" ON "Templates" ("ContentType");

CREATE INDEX "IX_Templates_CreatedBy" ON "Templates" ("CreatedBy");

CREATE INDEX "IX_Templates_CreatedOn" ON "Templates" ("CreatedOn");

CREATE INDEX "IX_Templates_DisplayName" ON "Templates" ("DisplayName");

CREATE INDEX "IX_Templates_Subject" ON "Templates" ("Subject");

CREATE INDEX "IX_Templates_TenantId" ON "Templates" ("TenantId");

CREATE UNIQUE INDEX "IX_Templates_TenantId_UniqueNameNormalized" ON "Templates" ("TenantId", "UniqueNameNormalized");

CREATE INDEX "IX_Templates_UniqueName" ON "Templates" ("UniqueName");

CREATE INDEX "IX_Templates_UpdatedBy" ON "Templates" ("UpdatedBy");

CREATE INDEX "IX_Templates_UpdatedOn" ON "Templates" ("UpdatedOn");

CREATE INDEX "IX_Templates_Version" ON "Templates" ("Version");

CREATE INDEX "IX_TokenBlacklist_ExpiresOn" ON "TokenBlacklist" ("ExpiresOn");

CREATE UNIQUE INDEX "IX_TokenBlacklist_Id" ON "TokenBlacklist" ("Id");

CREATE UNIQUE INDEX "IX_UserIdentifiers_Id" ON "UserIdentifiers" ("Id");

CREATE UNIQUE INDEX "IX_UserIdentifiers_TenantId_Key_Value" ON "UserIdentifiers" ("TenantId", "Key", "Value");

CREATE INDEX "IX_UserIdentifiers_UserId" ON "UserIdentifiers" ("UserId");

CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");

CREATE INDEX "IX_Users_AddressFormatted" ON "Users" ("AddressFormatted");

CREATE UNIQUE INDEX "IX_Users_AggregateId" ON "Users" ("AggregateId");

CREATE INDEX "IX_Users_AuthenticatedOn" ON "Users" ("AuthenticatedOn");

CREATE INDEX "IX_Users_Birthdate" ON "Users" ("Birthdate");

CREATE INDEX "IX_Users_CreatedBy" ON "Users" ("CreatedBy");

CREATE INDEX "IX_Users_CreatedOn" ON "Users" ("CreatedOn");

CREATE INDEX "IX_Users_DisabledOn" ON "Users" ("DisabledOn");

CREATE INDEX "IX_Users_EmailAddress" ON "Users" ("EmailAddress");

CREATE INDEX "IX_Users_FirstName" ON "Users" ("FirstName");

CREATE INDEX "IX_Users_FullName" ON "Users" ("FullName");

CREATE INDEX "IX_Users_Gender" ON "Users" ("Gender");

CREATE INDEX "IX_Users_HasPassword" ON "Users" ("HasPassword");

CREATE INDEX "IX_Users_IsConfirmed" ON "Users" ("IsConfirmed");

CREATE INDEX "IX_Users_IsDisabled" ON "Users" ("IsDisabled");

CREATE INDEX "IX_Users_LastName" ON "Users" ("LastName");

CREATE INDEX "IX_Users_Locale" ON "Users" ("Locale");

CREATE INDEX "IX_Users_MiddleName" ON "Users" ("MiddleName");

CREATE INDEX "IX_Users_Nickname" ON "Users" ("Nickname");

CREATE INDEX "IX_Users_PasswordChangedOn" ON "Users" ("PasswordChangedOn");

CREATE INDEX "IX_Users_PhoneE164Formatted" ON "Users" ("PhoneE164Formatted");

CREATE INDEX "IX_Users_TenantId" ON "Users" ("TenantId");

CREATE INDEX "IX_Users_TenantId_EmailAddressNormalized" ON "Users" ("TenantId", "EmailAddressNormalized");

CREATE UNIQUE INDEX "IX_Users_TenantId_UniqueNameNormalized" ON "Users" ("TenantId", "UniqueNameNormalized");

CREATE INDEX "IX_Users_TimeZone" ON "Users" ("TimeZone");

CREATE INDEX "IX_Users_UniqueName" ON "Users" ("UniqueName");

CREATE INDEX "IX_Users_UpdatedBy" ON "Users" ("UpdatedBy");

CREATE INDEX "IX_Users_UpdatedOn" ON "Users" ("UpdatedOn");

CREATE INDEX "IX_Users_Version" ON "Users" ("Version");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230918235543_Release_3_0_0', '7.0.10');

COMMIT;
