START TRANSACTION;

CREATE TABLE "TokenBlacklist" (
    "BlacklistedTokenId" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Id" uuid NOT NULL,
    "ExpiresOn" timestamp with time zone NULL,
    CONSTRAINT "PK_TokenBlacklist" PRIMARY KEY ("BlacklistedTokenId")
);

CREATE INDEX "IX_TokenBlacklist_ExpiresOn" ON "TokenBlacklist" ("ExpiresOn");

CREATE UNIQUE INDEX "IX_TokenBlacklist_Id" ON "TokenBlacklist" ("Id");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230902044902_CreateTokenBlacklistTable', '7.0.10');

COMMIT;
