START TRANSACTION;

CREATE TABLE "Senders" (
    "SenderId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255) NULL,
    "IsDefault" boolean NOT NULL,
    "EmailAddress" character varying(255) NOT NULL,
    "DisplayName" character varying(255) NULL,
    "Description" text NULL,
    "Provider" character varying(255) NOT NULL,
    "Settings" text NULL,
    "AggregateId" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_Senders" PRIMARY KEY ("SenderId")
);

CREATE UNIQUE INDEX "IX_Senders_AggregateId" ON "Senders" ("AggregateId");

CREATE INDEX "IX_Senders_CreatedBy" ON "Senders" ("CreatedBy");

CREATE INDEX "IX_Senders_CreatedOn" ON "Senders" ("CreatedOn");

CREATE INDEX "IX_Senders_DisplayName" ON "Senders" ("DisplayName");

CREATE INDEX "IX_Senders_EmailAddress" ON "Senders" ("EmailAddress");

CREATE INDEX "IX_Senders_Provider" ON "Senders" ("Provider");

CREATE INDEX "IX_Senders_TenantId" ON "Senders" ("TenantId");

CREATE UNIQUE INDEX "IX_Senders_TenantId_IsDefault" ON "Senders" ("TenantId", "IsDefault") WHERE "IsDefault" = true;

CREATE INDEX "IX_Senders_UpdatedBy" ON "Senders" ("UpdatedBy");

CREATE INDEX "IX_Senders_UpdatedOn" ON "Senders" ("UpdatedOn");

CREATE INDEX "IX_Senders_Version" ON "Senders" ("Version");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230911191009_CreateSenderTable', '7.0.10');

COMMIT;
