START TRANSACTION;

ALTER TABLE "Realms" ADD "PasswordRecoveryTemplateId" integer NULL;

CREATE TABLE "Templates" (
    "TemplateId" integer GENERATED BY DEFAULT AS IDENTITY,
    "TenantId" character varying(255) NULL,
    "UniqueName" character varying(255) NOT NULL,
    "UniqueNameNormalized" character varying(255) NOT NULL,
    "DisplayName" character varying(255) NULL,
    "Description" text NULL,
    "Subject" character varying(255) NOT NULL,
    "ContentType" character varying(16) NOT NULL,
    "Contents" text NOT NULL,
    "AggregateId" character varying(255) NOT NULL,
    "CreatedBy" character varying(255) NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "UpdatedBy" character varying(255) NOT NULL,
    "UpdatedOn" timestamp with time zone NOT NULL,
    "Version" bigint NOT NULL,
    CONSTRAINT "PK_Templates" PRIMARY KEY ("TemplateId")
);

CREATE UNIQUE INDEX "IX_Realms_PasswordRecoveryTemplateId" ON "Realms" ("PasswordRecoveryTemplateId");

CREATE UNIQUE INDEX "IX_Templates_AggregateId" ON "Templates" ("AggregateId");

CREATE INDEX "IX_Templates_ContentType" ON "Templates" ("ContentType");

CREATE INDEX "IX_Templates_CreatedBy" ON "Templates" ("CreatedBy");

CREATE INDEX "IX_Templates_CreatedOn" ON "Templates" ("CreatedOn");

CREATE INDEX "IX_Templates_DisplayName" ON "Templates" ("DisplayName");

CREATE INDEX "IX_Templates_Subject" ON "Templates" ("Subject");

CREATE INDEX "IX_Templates_TenantId" ON "Templates" ("TenantId");

CREATE UNIQUE INDEX "IX_Templates_TenantId_UniqueNameNormalized" ON "Templates" ("TenantId", "UniqueNameNormalized");

CREATE INDEX "IX_Templates_UniqueName" ON "Templates" ("UniqueName");

CREATE INDEX "IX_Templates_UpdatedBy" ON "Templates" ("UpdatedBy");

CREATE INDEX "IX_Templates_UpdatedOn" ON "Templates" ("UpdatedOn");

CREATE INDEX "IX_Templates_Version" ON "Templates" ("Version");

ALTER TABLE "Realms" ADD CONSTRAINT "FK_Realms_Templates_PasswordRecoveryTemplateId" FOREIGN KEY ("PasswordRecoveryTemplateId") REFERENCES "Templates" ("TemplateId") ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230913031516_CreateTemplateTable', '7.0.10');

COMMIT;
