-- No dependencies
DROP TABLE IF EXISTS "Actors" CASCADE;
DROP TABLE IF EXISTS "LogEvents" CASCADE;
DROP TABLE IF EXISTS "Logs" CASCADE;
DROP TABLE IF EXISTS "TokenBlacklist" CASCADE;
-- Emails
DROP TABLE IF EXISTS "Dictionaries" CASCADE;
DROP TABLE IF EXISTS "Senders" CASCADE;
DROP TABLE IF EXISTS "Templates" CASCADE;
DROP TABLE IF EXISTS "Messages" CASCADE;
DROP TABLE IF EXISTS "Recipients" CASCADE;
-- User related tables
DROP TABLE IF EXISTS "Sessions" CASCADE;
DROP TABLE IF EXISTS "UserIdentifiers" CASCADE;
DROP TABLE IF EXISTS "UserRoles" CASCADE;
DROP TABLE IF EXISTS "Users" CASCADE;
DROP TABLE IF EXISTS "ApiKeyRoles" CASCADE;
DROP TABLE IF EXISTS "ApiKeys" CASCADE;
DROP TABLE IF EXISTS "Roles" CASCADE;
DROP TABLE IF EXISTS "Realms" CASCADE;
-- Event Sourcing
DROP TABLE IF EXISTS "Events" CASCADE;
-- EntityFrameworkCore migrations
DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;
