name: Publish Docker Image to Docker Hub & NuGet Packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish Docker Image to Docker Hub & NuGet Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --filter Category=Unit

      - name: Build Portal Frontend
        run: |
          cd ./frontend
          npm clean-install
          npm run build
          cd ../

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: fpion/portal

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          file: backend/src/Logitar.Portal/Dockerfile
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Push NuGet
        run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json
