name: Deploy Staging Portal to Azure

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: francispion.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          cd ./frontend
          npm ci
          npm run build:staging
          cd ../backend
          docker build . -t francispion.azurecr.io/portal:${{ github.sha }} -f src/Portal.Web/Dockerfile
          docker push francispion.azurecr.io/portal:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'staging-portal'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_STAGING }}
          images: 'francispion.azurecr.io/portal:${{ github.sha }}'
